export const FIND_FILE_TWO = 'FIND_FILE_TWO'
export const CURRENT_PAGE = 'CURRENT_PAGE'
export const TWO_MENU = 'TWO_MENU'
export const THREE_MENU = 'THREE_MENU'
export const BACK = 'BACK'
export const PAGE_TWO = 'PAGE_TWO'
export const AUTO_TWO = 'AUTO_TWO'
export const CURRENT_TWO = 'CURRENT_TWO'