export const FIND_FILE_ONE = 'FIND_FILE_ONE'
export const CURRENT_PAGE = 'CURRENT_PAGE'
export const TWO_MENU = 'TWO_MENU'
export const THREE_MENU = 'THREE_MENU'
export const BACK = 'BACK'
export const PAGE_ONE = 'PAGE_ONE'
export const AUTO_ONE = 'AUTO_ONE'
export const CURRENT_ONE = 'CURRENT_ONE'